all: getall core test cover vet lint
	go build  -tags command ./...

vet:
	go vet -tags command ./...

lint:
	golint ./...

core:
	go build ./...

test:
	go test ./...

clean:
	go clean ./...

cover:
	go test -v -covermode=count -coverprofile=coverage.out ./...
	goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ${COVERALLS_TOKEN}

getall:
	go get -v -tags command ./...
